spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:./db;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    initialization-mode: always
    platform: h2
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false